"""Generate index.html from the cut list below. Edit CUTS, then: python3 scripts/build.py"""
from pathlib import Path

# (source clip, in-point seconds, length seconds, transition INTO this shot)
# transitions: "punch" = fast zoom-blur punch-in, "whip" = horizontal whip pan + whoosh
CUTS = [
    ("IMG_3117",   1.8, 1.5, None),     # clothes thrown across closet (hook)
    ("IMG_3117_2", 3.0, 1.6, "punch"),  # turns to camera
    ("IMG_3117_2", 21.0, 1.2, "punch"), # tightening waistband, close
    ("IMG_3118",   0.0, 1.4, "whip"),   # POV walking out — chapter: outside
    ("IMG_3118",   3.3, 1.5, "punch"),  # opening the gate
    ("IMG_3119",   1.6, 2.0, "punch"),  # opening the car door
    ("IMG_3121",   1.0, 2.0, "whip"),   # hand on wheel, trees — chapter: drive
    ("IMG_3122",   2.8, 1.8, "punch"),  # selfie, hand through hair
    ("IMG_3123",   2.5, 2.0, "punch"),  # tree-lined country road
    ("IMG_3124",   3.5, 1.8, "punch"),  # side mirror over fields
    ("IMG_3125",   1.0, 2.0, "punch"),  # arriving at the building
    ("IMG_3128",   0.8, 1.5, "whip"),   # backgammon — chapter: inside
    ("IMG_3129",   0.4, 1.6, "punch"),  # dice throw
    ("IMG_3130",   0.0, 2.0, "punch"),  # desk push-up
    ("IMG_3131",   0.5, 2.7, "punch"),  # peanuts close-up (outro)
]
MUSIC_OFFSET = 24.0   # skip the bed's slow intro so it's already moving
FADE_OUT = 0.6

starts, t = [], 0.0
for c in CUTS:
    starts.append(round(t, 3))
    t += c[2]
TOTAL = round(t, 3)

videos, tweens, sfx = [], [], []
for i, ((src, mi, d, tr), s) in enumerate(zip(CUTS, starts)):
    track = i % 2  # alternate tracks so neighbouring clips never collide
    videos.append(
        f'      <div class="shot" id="w{i}"><div class="fx" id="x{i}">\n'
        f'        <video id="v{i}" src="assets/raw/{src}.mp4" muted playsinline\n'
        f'          data-start="{s}" data-duration="{d}" data-media-start="{mi}" data-track-index="{track}"></video>\n'
        f'      </div></div>'
    )
    # slow push-in on every shot so the camera never sits still
    tweens.append(f'      tl.fromTo("#w{i}", {{ scale: 1.04 }}, {{ scale: 1.1, duration: {d}, ease: "none" }}, {s});')
    if tr == "punch":
        tweens.append(f'      tl.from("#x{i}", {{ scale: 1.18, filter: "blur(10px) brightness(1.25)", duration: 0.28, ease: "expo.out" }}, {s});')
    elif tr == "whip":
        prev = i - 1
        tweens.append(f'      tl.to("#x{prev}", {{ x: -420, filter: "blur(28px)", duration: 0.14, ease: "power3.in" }}, {round(s - 0.14, 3)});')
        tweens.append(f'      tl.from("#x{i}", {{ x: 420, filter: "blur(28px)", duration: 0.22, ease: "power3.out" }}, {s});')
        tweens.append(f'      tl.to("#flash", {{ opacity: 0.35, duration: 0.07, yoyo: true, repeat: 1, ease: "sine.inOut" }}, {round(s - 0.07, 3)});')
        sfx.append(
            f'    <audio id="sfx{i}" src="assets/whoosh.mp3" data-start="{round(s - 0.25, 3)}" data-duration="0.57" '
            f'data-track-index="{10 + len(sfx) % 2}" data-volume="0.45"></audio>'
        )
tweens.append(f'      tl.to("#fade", {{ opacity: 1, duration: {FADE_OUT}, ease: "power1.in" }}, {round(TOTAL - FADE_OUT, 3)});')

html = f"""<!doctype html>
<html lang="en" data-resolution="portrait">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <!-- GENERATED by scripts/build.py — edit the cut list there, not this file -->
    <script src="assets/gsap.min.js"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: 1080px; height: 1920px; overflow: hidden; background: #000; }}
      #root {{ position: relative; width: 100%; height: 100%; overflow: hidden; background: #000; }}
      .shot, .fx {{ position: absolute; inset: 0; overflow: hidden; }}
      .shot video {{
        width: 100%; height: 100%; object-fit: cover; display: block;
        /* light unifying grade: a touch more contrast + warmth */
        filter: contrast(1.06) saturate(1.08) sepia(0.06);
      }}
      #vignette {{
        position: absolute; inset: 0; pointer-events: none; z-index: 5;
        background: radial-gradient(ellipse at center, rgba(0,0,0,0) 55%, rgba(0,0,0,0.45) 100%);
      }}
      #flash {{ position: absolute; inset: 0; background: #fff; opacity: 0; pointer-events: none; z-index: 6; }}
      #fade {{ position: absolute; inset: 0; background: #000; opacity: 0; pointer-events: none; z-index: 7; }}
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="{TOTAL}" data-width="1080" data-height="1920">
{chr(10).join(videos)}
      <div id="vignette"></div>
      <div id="flash"></div>
      <div id="fade"></div>
    </div>
    <audio id="music" src="assets/music.mp3" data-start="0" data-duration="{TOTAL}" data-media-start="{MUSIC_OFFSET}" data-track-index="9" data-volume="0.55"></audio>
{chr(10).join(sfx)}
    <script>
      window.__timelines = window.__timelines || {{}};
      const tl = gsap.timeline({{ paused: true }});
{chr(10).join(tweens)}
      tl.set({{}}, {{}}, {TOTAL});
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
"""
Path(__file__).resolve().parent.parent.joinpath("index.html").write_text(html)
print(f"wrote index.html — {len(CUTS)} shots, {TOTAL}s")
